-- PostgreSQL 14+
-- Cargue este archivo como una sola transacción. En producción, la conexión
-- de la aplicación debe usar un rol sin SUPERUSER/BYPASSRLS y distinto al dueño.
BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

DO $$ BEGIN CREATE TYPE public.estado_asamblea AS ENUM ('programada','activa','cerrada');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;
DO $$ BEGIN CREATE TYPE public.estado_pregunta AS ENUM ('inactiva','activa','cerrada');
EXCEPTION WHEN duplicate_object THEN NULL; END $$;

CREATE TABLE IF NOT EXISTS public.copropiedades (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  nombre VARCHAR(180) NOT NULL,
  nit VARCHAR(24) NOT NULL UNIQUE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT copropiedades_nombre_no_vacio CHECK (length(trim(nombre)) > 0)
);

CREATE TABLE IF NOT EXISTS public.unidades (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  id_copropiedad UUID NOT NULL REFERENCES public.copropiedades(id) ON DELETE RESTRICT,
  numero_inmueble VARCHAR(120) NOT NULL,
  coeficiente NUMERIC(9,6) NOT NULL,
  -- Caché operativa solicitada. El dato histórico por reunión está en asistencia_asambleas.
  estado_asistencia BOOLEAN NOT NULL DEFAULT FALSE,
  creado_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT unidades_coeficiente_valido CHECK (coeficiente > 0 AND coeficiente <= 100),
  CONSTRAINT unidades_numero_por_copropiedad UNIQUE (id_copropiedad, numero_inmueble),
  CONSTRAINT unidades_id_tenant_unique UNIQUE (id, id_copropiedad)
);

CREATE TABLE IF NOT EXISTS public.asambleas (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  id_copropiedad UUID NOT NULL REFERENCES public.copropiedades(id) ON DELETE RESTRICT,
  fecha TIMESTAMPTZ NOT NULL,
  estado public.estado_asamblea NOT NULL DEFAULT 'programada',
  creada_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT asambleas_id_tenant_unique UNIQUE (id, id_copropiedad)
);

CREATE UNIQUE INDEX IF NOT EXISTS una_asamblea_activa_por_copropiedad
  ON public.asambleas(id_copropiedad) WHERE estado = 'activa';

CREATE TABLE IF NOT EXISTS public.preguntas (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_asamblea UUID NOT NULL,
  id_copropiedad UUID NOT NULL,
  enunciado VARCHAR(1000) NOT NULL,
  estado public.estado_pregunta NOT NULL DEFAULT 'inactiva',
  -- Umbrales opcionales por decisión; no se presume una mayoría universal.
  umbral_quorum_porcentaje NUMERIC(9,6),
  umbral_aprobacion_porcentaje NUMERIC(9,6),
  creada_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT preguntas_enunciado_no_vacio CHECK (length(trim(enunciado)) > 0),
  CONSTRAINT preguntas_enunciado_por_asamblea UNIQUE (id_asamblea,enunciado),
  CONSTRAINT preguntas_umbral_quorum CHECK (umbral_quorum_porcentaje IS NULL OR umbral_quorum_porcentaje BETWEEN 0 AND 100),
  CONSTRAINT preguntas_umbral_aprobacion CHECK (umbral_aprobacion_porcentaje IS NULL OR umbral_aprobacion_porcentaje BETWEEN 0 AND 100),
  CONSTRAINT preguntas_asamblea_tenant_fk FOREIGN KEY (id_asamblea,id_copropiedad)
    REFERENCES public.asambleas(id,id_copropiedad) ON DELETE RESTRICT,
  CONSTRAINT preguntas_id_asamblea_tenant_unique UNIQUE (id,id_asamblea,id_copropiedad)
);

CREATE UNIQUE INDEX IF NOT EXISTS una_pregunta_activa_por_asamblea
  ON public.preguntas(id_asamblea) WHERE estado = 'activa';

CREATE TABLE IF NOT EXISTS public.opciones (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  id_pregunta INTEGER NOT NULL,
  id_asamblea UUID NOT NULL,
  id_copropiedad UUID NOT NULL,
  texto VARCHAR(300) NOT NULL,
  orden SMALLINT NOT NULL DEFAULT 1,
  CONSTRAINT opciones_texto_no_vacio CHECK (length(trim(texto)) > 0),
  CONSTRAINT opciones_orden_positivo CHECK (orden > 0),
  CONSTRAINT opciones_pregunta_tenant_fk FOREIGN KEY (id_pregunta,id_asamblea,id_copropiedad)
    REFERENCES public.preguntas(id,id_asamblea,id_copropiedad) ON DELETE RESTRICT,
  CONSTRAINT opciones_id_pregunta_asamblea_tenant_unique UNIQUE (id,id_pregunta,id_asamblea,id_copropiedad),
  CONSTRAINT opciones_orden_unico UNIQUE (id_pregunta,orden),
  CONSTRAINT opciones_texto_unico_ci UNIQUE (id_pregunta,texto)
);

ALTER TABLE public.opciones DROP CONSTRAINT IF EXISTS opciones_texto_unico_ci;
CREATE UNIQUE INDEX IF NOT EXISTS opciones_texto_unico_ci
  ON public.opciones(id_pregunta,lower(texto));

CREATE TABLE IF NOT EXISTS public.asistencia_asambleas (
  id_asamblea UUID NOT NULL,
  id_copropiedad UUID NOT NULL,
  id_unidad UUID NOT NULL,
  estado_asistencia BOOLEAN NOT NULL DEFAULT FALSE,
  registrada_en TIMESTAMPTZ,
  ultima_conexion_socket_en TIMESTAMPTZ,
  actualizada_en TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (id_asamblea,id_unidad),
  CONSTRAINT asistencia_asamblea_tenant_fk FOREIGN KEY (id_asamblea,id_copropiedad)
    REFERENCES public.asambleas(id,id_copropiedad) ON DELETE RESTRICT,
  CONSTRAINT asistencia_unidad_tenant_fk FOREIGN KEY (id_unidad,id_copropiedad)
    REFERENCES public.unidades(id,id_copropiedad) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS public.votos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  id_pregunta INTEGER NOT NULL,
  id_asamblea UUID NOT NULL,
  id_copropiedad UUID NOT NULL,
  id_unidad UUID NOT NULL,
  id_opcion INTEGER NOT NULL,
  coeficiente_registrado NUMERIC(9,6) NOT NULL,
  registrado_en TIMESTAMPTZ NOT NULL DEFAULT clock_timestamp(),
  CONSTRAINT votos_coeficiente_valido CHECK (coeficiente_registrado > 0 AND coeficiente_registrado <= 100),
  CONSTRAINT votos_una_unidad_por_pregunta UNIQUE (id_pregunta,id_unidad),
  CONSTRAINT votos_pregunta_tenant_fk FOREIGN KEY (id_pregunta,id_asamblea,id_copropiedad)
    REFERENCES public.preguntas(id,id_asamblea,id_copropiedad) ON DELETE RESTRICT,
  CONSTRAINT votos_opcion_de_pregunta_fk FOREIGN KEY (id_opcion,id_pregunta,id_asamblea,id_copropiedad)
    REFERENCES public.opciones(id,id_pregunta,id_asamblea,id_copropiedad) ON DELETE RESTRICT,
  CONSTRAINT votos_unidad_tenant_fk FOREIGN KEY (id_unidad,id_copropiedad)
    REFERENCES public.unidades(id,id_copropiedad) ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_unidades_tenant ON public.unidades(id_copropiedad);
CREATE INDEX IF NOT EXISTS idx_asambleas_tenant_estado ON public.asambleas(id_copropiedad,estado);
CREATE INDEX IF NOT EXISTS idx_preguntas_asamblea_estado ON public.preguntas(id_copropiedad,id_asamblea,estado);
CREATE INDEX IF NOT EXISTS idx_votos_resultados ON public.votos(id_copropiedad,id_pregunta,id_opcion);
CREATE INDEX IF NOT EXISTS idx_asistencia_quorum ON public.asistencia_asambleas(id_copropiedad,id_asamblea,estado_asistencia);

CREATE OR REPLACE FUNCTION public.validar_suma_coeficientes_copropiedad()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE
  tenants UUID[];
  tenant_id UUID;
  cantidad BIGINT;
  suma NUMERIC(12,6);
BEGIN
  IF TG_TABLE_NAME = 'copropiedades' THEN
    IF TG_OP = 'DELETE' THEN tenants := ARRAY[OLD.id];
    ELSE tenants := ARRAY[NEW.id];
    END IF;
  ELSE
    IF TG_OP = 'INSERT' THEN tenants := ARRAY[NEW.id_copropiedad];
    ELSIF TG_OP = 'DELETE' THEN tenants := ARRAY[OLD.id_copropiedad];
    ELSE tenants := ARRAY[OLD.id_copropiedad,NEW.id_copropiedad];
    END IF;
  END IF;

  FOREACH tenant_id IN ARRAY tenants LOOP
    IF tenant_id IS NOT NULL AND EXISTS (SELECT 1 FROM public.copropiedades c WHERE c.id=tenant_id) THEN
      SELECT count(*),COALESCE(sum(u.coeficiente),0)
        INTO cantidad,suma FROM public.unidades u WHERE u.id_copropiedad=tenant_id;
      IF cantidad=0 OR suma <> 100.000000 THEN
        RAISE EXCEPTION 'Los coeficientes de la copropiedad % deben sumar exactamente 100.000000 (actual: %)',tenant_id,suma
          USING ERRCODE='23514', CONSTRAINT='coeficientes_copropiedad_suman_100';
      END IF;
    END IF;
  END LOOP;
  RETURN NULL;
END $$;

DROP TRIGGER IF EXISTS validar_coeficientes_unidad ON public.unidades;
DROP TRIGGER IF EXISTS validar_coeficientes_copropiedad ON public.copropiedades;

CREATE CONSTRAINT TRIGGER validar_coeficientes_unidad
AFTER INSERT OR UPDATE OR DELETE ON public.unidades
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
EXECUTE FUNCTION public.validar_suma_coeficientes_copropiedad();

CREATE CONSTRAINT TRIGGER validar_coeficientes_copropiedad
AFTER INSERT OR UPDATE OR DELETE ON public.copropiedades
DEFERRABLE INITIALLY DEFERRED FOR EACH ROW
EXECUTE FUNCTION public.validar_suma_coeficientes_copropiedad();

CREATE OR REPLACE FUNCTION public.rechazar_mutacion_voto()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN  RAISE EXCEPTION 'Los votos son inmutables; no se permiten UPDATE ni DELETE'
    USING ERRCODE='55000';
END $$;

DROP TRIGGER IF EXISTS votos_inmutables ON public.votos;
CREATE TRIGGER votos_inmutables
BEFORE UPDATE OR DELETE ON public.votos
FOR EACH ROW EXECUTE FUNCTION public.rechazar_mutacion_voto();

-- RLS usa SET LOCAL app.id_copropiedad por transacción (ver withTenantTransaction en voting.controller.ts).
ALTER TABLE public.copropiedades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.unidades ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asambleas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.preguntas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.opciones ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.asistencia_asambleas ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.votos ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS tenant_copropiedades ON public.copropiedades;
CREATE POLICY tenant_copropiedades ON public.copropiedades
  USING (id=NULLIF(current_setting('app.id_copropiedad',true),'')::uuid)
  WITH CHECK (id=NULLIF(current_setting('app.id_copropiedad',true),'')::uuid);
DROP POLICY IF EXISTS tenant_unidades ON public.unidades;
CREATE POLICY tenant_unidades ON public.unidades
  USING (id_copropiedad=NULLIF(current_setting('app.id_copropiedad',true),'')::uuid)
  WITH CHECK (id_copropiedad=NULLIF(current_setting('app.id_copropiedad',true),'')::uuid);
DROP POLICY IF EXISTS tenant_asambleas ON public.asambleas;
CREATE POLICY tenant_asambleas ON public.asambleas
  USING (id_copropiedad=NULLIF(current_setting('app.id_copropiedad',true),'')::uuid)
  WITH CHECK (id_copropiedad=NULLIF(current_setting('app.id_copropiedad',true),'')::uuid);
DROP POLICY IF EXISTS tenant_preguntas ON public.preguntas;
CREATE POLICY tenant_preguntas ON public.preguntas
  USING (id_copropiedad=NULLIF(current_setting('app.id_copropiedad',true),'')::uuid)
  WITH CHECK (id_copropiedad=NULLIF(current_setting('app.id_copropiedad',true),'')::uuid);
DROP POLICY IF EXISTS tenant_opciones ON public.opciones;
CREATE POLICY tenant_opciones ON public.opciones
  USING (id_copropiedad=NULLIF(current_setting('app.id_copropiedad',true),'')::uuid)
  WITH CHECK (id_copropiedad=NULLIF(current_setting('app.id_copropiedad',true),'')::uuid);
DROP POLICY IF EXISTS tenant_asistencia ON public.asistencia_asambleas;
CREATE POLICY tenant_asistencia ON public.asistencia_asambleas
  USING (id_copropiedad=NULLIF(current_setting('app.id_copropiedad',true),'')::uuid)
  WITH CHECK (id_copropiedad=NULLIF(current_setting('app.id_copropiedad',true),'')::uuid);
DROP POLICY IF EXISTS tenant_votos ON public.votos;
CREATE POLICY tenant_votos ON public.votos
  USING (id_copropiedad=NULLIF(current_setting('app.id_copropiedad',true),'')::uuid)
  WITH CHECK (id_copropiedad=NULLIF(current_setting('app.id_copropiedad',true),'')::uuid);

-- Se omite el seed demostrativo para no crear copropiedades ficticias en producción.
COMMIT;
